### ISSUE TITLE
Objects Not Visible

### ISSUE THREAD

**Issue by Simsomsim** [Syroot/io_scene_bfres#3]
Get an error every time an szs or bfres is imported (see attached), and then the imported object has no model. This also occurs with byaml files, but I assume that is because the bfres is broken (gets the same error). The only thing that shows is the axes (three perpendicular lines with x, y, z), which can be moved like a normal object. Files exported from this do not work in-game, understandably. Another person has had this problem and was unable to find a solution. Multiple Blender versions have been tried, and re-downloading the addons has been attempted, too.

![](https://user-images.githubusercontent.com/36491920/36233121-7743847c-11b2-11e8-9673-1d163bfec4f4.PNG)

**Comment by RayKoopa** [comment]
What do you mean with multiple versions? Old versions are not supported. You probably did not set up TexConv correctly. Please check the wiki on how to set it up and provide your configuration.

**Comment by Simsomsim** [comment]
Thank you so much, a quick re-install of TexConv2.exe solved everything. For some reason the file I had for it originally didn't work.
