### ISSUE TITLE
report: error

### ISSUE THREAD

**Issue by roland3564** [Syroot/io_scene_bfres#4]
when i try to import a bfres model with texconv2 it says:
traceback: file importing.py, line 64 in execute return.importer.run
file importing.py, line 99 in run self_convert(bfres)
file importing.py line 105 in_convert for ftex_node in bfres.ftex_index_group[1:]
attributerror bfresfile object has no attribute ftex_index_group

[error zip.zip](https://github.com/Syroot/io_scene_bfres/files/1752528/error.zip.zip)

**Comment by RayKoopa** [comment]
Which BFRES model version are you trying to load? Or of which game are you trying to load models from? The add-on is really outdated and only mostly supports Mario Kart 8.

**Comment by roland3564** [comment]
zelda breath of the wild

**Comment by RayKoopa** [comment]
The model format of BotW is slightly newer and some aspects are not supported.
It is probably fixed in the C# library. Since this addon isn't really supported anymore, you can try simply patching around not iterating over the the ftex_index_group if there is none.

**Comment by roland3564** [comment]
i can't use 3ds max is there another way to make models?

**Comment by RayKoopa** [comment]
None I offer. You can write converters with my [C# lib](https://github.com/Syroot/NintenTools.Bfres) if you wanted to.
