### ISSUE TITLE
Bones

### ISSUE THREAD

**Issue by mrpoppagiorgio** [Syroot/io_scene_bfres#5]
When I import into blender I don't see how to access the bones. Are they not importing?

**Comment by RayKoopa** [comment]
No, skeletons and bones are not supported. https://github.com/Syroot/io_scene_bfres/wiki/Supported-Features

**Comment by mrpoppagiorgio** [comment]
Are you hoping to add this in the future?

**Comment by RayKoopa** [comment]
The current state of the project can be found in the link I posted above. It's currently not actively being worked on.
